import { Template } from '@/types';

/**
 * 預設邀請函範本資料
 * 包含 3-5 個設計好的範本，每個範本都有預設元件配置
 */

export const MOCK_TEMPLATES: Template[] = [
  {
    id: 'template-wedding-1',
    name: '浪漫婚禮',
    description: '優雅的婚禮邀請函範本，適合正式婚禮使用',
    thumbnail: '/templates/wedding-1.jpg',
    canvasSize: { width: 375, height: 667 },
    elements: [
      // 背景圖片
      {
        id: 'bg-1',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=400&h=700&fit=crop',
        alt: '婚禮背景',
        isBackground: true,
        x: 0,
        y: 0,
        width: 375,
        height: 667,
        zIndex: 0
      },
      // 標題文字
      {
        id: 'text-1',
        type: 'text',
        content: '我們結婚了',
        x: 75,
        y: 100,
        width: 225,
        height: 60,
        zIndex: 1,
        fontSize: 36,
        fontFamily: 'serif',
        color: '#ffffff',
        fontWeight: 700,
        textAlign: 'center',
      },
      // 新郎新娘姓名
      {
        id: 'text-2',
        type: 'text',
        content: 'John & Mary',
        x: 75,
        y: 180,
        width: 225,
        height: 40,
        zIndex: 1,
        fontSize: 28,
        fontFamily: 'cursive',
        color: '#ffffff',
        fontWeight: 400,
        textAlign: 'center',
      },
      // 日期時間
      {
        id: 'text-3',
        type: 'text',
        content: '2024.12.25\n下午 2:00',
        x: 100,
        y: 400,
        width: 175,
        height: 60,
        zIndex: 1,
        fontSize: 20,
        fontFamily: 'sans-serif',
        color: '#ffffff',
        fontWeight: 500,
        textAlign: 'center',
      },
      // 地點
      {
        id: 'text-4',
        type: 'text',
        content: '台北君悅酒店',
        x: 100,
        y: 480,
        width: 175,
        height: 30,
        zIndex: 1,
        fontSize: 18,
        fontFamily: 'sans-serif',
        color: '#ffffff',
        fontWeight: 400,
        textAlign: 'center',
      },
      // RSVP 表單
      {
        id: 'rsvp-1',
        type: 'rsvp-form',
        x: 37,
        y: 550,
        width: 300,
        height: 80,
        zIndex: 1,
        fields: {
          name: true,
          email: true,
          attendance: true,
        },
      },
    ],
  },
  {
    id: 'template-birthday-1',
    name: '生日派對',
    description: '活潑有趣的生日派對邀請函，適合各年齡層',
    thumbnail: '/templates/birthday-1.jpg',
    canvasSize: { width: 375, height: 667 },
    elements: [
      // 背景顏色（使用漸層圖片模擬）
      {
        id: 'bg-1',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=400&h=700&fit=crop',
        alt: '生日背景',
        isBackground: true,
        x: 0,
        y: 0,
        width: 375,
        height: 667,
        zIndex: 0
      },
      // 主標題
      {
        id: 'text-1',
        type: 'text',
        content: '🎉 生日快樂 🎉',
        x: 50,
        y: 120,
        width: 275,
        height: 70,
        zIndex: 1,
        fontSize: 42,
        fontFamily: 'sans-serif',
        color: '#ff6b9d',
        fontWeight: 800,
        textAlign: 'center',
      },
      // 姓名
      {
        id: 'text-2',
        type: 'text',
        content: '誠摯邀請您參加\nSarah 的生日派對',
        x: 50,
        y: 220,
        width: 275,
        height: 80,
        zIndex: 1,
        fontSize: 24,
        fontFamily: 'sans-serif',
        color: '#333333',
        fontWeight: 600,
        textAlign: 'center',
      },
      // 裝飾圖片
      {
        id: 'img-1',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=200&h=200&fit=crop',
        alt: '生日蛋糕',
        isBackground: false,
        x: 137,
        y: 320,
        width: 100,
        height: 100,
        zIndex: 1
      },
      // 日期時間
      {
        id: 'text-3',
        type: 'text',
        content: '2024/11/15 (五)\n晚上 7:00',
        x: 100,
        y: 440,
        width: 175,
        height: 60,
        zIndex: 1,
        fontSize: 20,
        fontFamily: 'sans-serif',
        color: '#333333',
        fontWeight: 500,
        textAlign: 'center',
      },
      // 地點
      {
        id: 'text-4',
        type: 'text',
        content: '📍 信義區微風廣場',
        x: 75,
        y: 520,
        width: 225,
        height: 30,
        zIndex: 1,
        fontSize: 18,
        fontFamily: 'sans-serif',
        color: '#333333',
        fontWeight: 400,
        textAlign: 'center',
      },
      // RSVP 表單
      {
        id: 'rsvp-1',
        type: 'rsvp-form',
        x: 37,
        y: 570,
        width: 300,
        height: 80,
        zIndex: 1,
        fields: {
          name: true,
          email: true,
          attendance: true,
        },
      },
    ],
  },
  {
    id: 'template-business-1',
    name: '商務活動',
    description: '專業的商務活動邀請函，適合企業會議與活動',
    thumbnail: '/templates/business-1.jpg',
    canvasSize: { width: 375, height: 667 },
    elements: [
      // 背景
      {
        id: 'bg-1',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=400&h=700&fit=crop',
        alt: '商務背景',
        isBackground: true,
        x: 0,
        y: 0,
        width: 375,
        height: 667,
        zIndex: 0
      },
      // 標題
      {
        id: 'text-1',
        type: 'text',
        content: '2024 年度高峰會',
        x: 50,
        y: 150,
        width: 275,
        height: 60,
        zIndex: 1,
        fontSize: 32,
        fontFamily: 'sans-serif',
        color: '#1e3a8a',
        fontWeight: 700,
        textAlign: 'center',
      },
      // 副標題
      {
        id: 'text-2',
        type: 'text',
        content: '創新 · 轉型 · 永續',
        x: 75,
        y: 230,
        width: 225,
        height: 40,
        zIndex: 1,
        fontSize: 20,
        fontFamily: 'sans-serif',
        color: '#64748b',
        fontWeight: 500,
        textAlign: 'center',
      },
      // 內容描述
      {
        id: 'text-3',
        type: 'text',
        content: '誠摯邀請您參加本年度最重要的產業盛會，與業界領袖共同探討未來趨勢。',
        x: 50,
        y: 300,
        width: 275,
        height: 100,
        zIndex: 1,
        fontSize: 16,
        fontFamily: 'sans-serif',
        color: '#475569',
        fontWeight: 400,
        textAlign: 'center',
      },
      // 日期時間
      {
        id: 'text-4',
        type: 'text',
        content: '2024年12月10日\n上午 9:00 - 下午 5:00',
        x: 75,
        y: 420,
        width: 225,
        height: 60,
        zIndex: 1,
        fontSize: 18,
        fontFamily: 'sans-serif',
        color: '#1e3a8a',
        fontWeight: 600,
        textAlign: 'center',
      },
      // 地點
      {
        id: 'text-5',
        type: 'text',
        content: '台北國際會議中心',
        x: 100,
        y: 500,
        width: 175,
        height: 30,
        zIndex: 1,
        fontSize: 18,
        fontFamily: 'sans-serif',
        color: '#1e3a8a',
        fontWeight: 500,
        textAlign: 'center',
      },
      // RSVP 表單
      {
        id: 'rsvp-1',
        type: 'rsvp-form',
        x: 37,
        y: 560,
        width: 300,
        height: 80,
        zIndex: 1,
        fields: {
          name: true,
          email: true,
          attendance: true,
        },
      },
    ],
  },
  {
    id: 'template-simple-1',
    name: '簡約風格',
    description: '簡潔優雅的設計，適合各種場合',
    thumbnail: '/templates/simple-1.jpg',
    canvasSize: { width: 375, height: 667 },
    elements: [
      // 純色背景
      {
        id: 'bg-1',
        type: 'image',
        src: 'data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="375" height="667"%3E%3Crect fill="%23f8fafc" width="375" height="667"/%3E%3C/svg%3E',
        alt: '純色背景',
        isBackground: true,
        x: 0,
        y: 0,
        width: 375,
        height: 667,
        zIndex: 0
      },
      // 標題
      {
        id: 'text-1',
        type: 'text',
        content: 'You are invited',
        x: 75,
        y: 200,
        width: 225,
        height: 50,
        zIndex: 1,
        fontSize: 32,
        fontFamily: 'serif',
        color: '#1e293b',
        fontWeight: 400,
        textAlign: 'center',
      },
      // 分隔線（用文字模擬）
      {
        id: 'text-2',
        type: 'text',
        content: '—————',
        x: 137,
        y: 260,
        width: 100,
        height: 20,
        zIndex: 1,
        fontSize: 24,
        fontFamily: 'sans-serif',
        color: '#cbd5e1',
        fontWeight: 300,
        textAlign: 'center',
      },
      // 活動名稱
      {
        id: 'text-3',
        type: 'text',
        content: '特別活動',
        x: 125,
        y: 300,
        width: 125,
        height: 40,
        zIndex: 1,
        fontSize: 24,
        fontFamily: 'sans-serif',
        color: '#64748b',
        fontWeight: 500,
        textAlign: 'center',
      },
      // 日期
      {
        id: 'text-4',
        type: 'text',
        content: '2024 / 12 / 31',
        x: 112,
        y: 380,
        width: 150,
        height: 30,
        zIndex: 1,
        fontSize: 20,
        fontFamily: 'sans-serif',
        color: '#94a3b8',
        fontWeight: 400,
        textAlign: 'center',
      },
      // 時間
      {
        id: 'text-5',
        type: 'text',
        content: '18:00',
        x: 150,
        y: 420,
        width: 75,
        height: 30,
        zIndex: 1,
        fontSize: 20,
        fontFamily: 'sans-serif',
        color: '#94a3b8',
        fontWeight: 400,
        textAlign: 'center',
      },
      // RSVP 表單
      {
        id: 'rsvp-1',
        type: 'rsvp-form',
        x: 37,
        y: 520,
        width: 300,
        height: 80,
        zIndex: 1,
        fields: {
          name: true,
          email: true,
          attendance: true,
        },
      },
    ],
  },
  {
    id: 'template-modern-1',
    name: '現代藝術',
    description: '充滿創意的現代藝術風格邀請函',
    thumbnail: '/templates/modern-1.jpg',
    canvasSize: { width: 375, height: 667 },
    elements: [
      // 背景
      {
        id: 'bg-1',
        type: 'image',
        src: 'https://images.unsplash.com/photo-1557672172-298e090bd0f1?w=400&h=700&fit=crop',
        alt: '現代背景',
        isBackground: true,
        x: 0,
        y: 0,
        width: 375,
        height: 667,
        zIndex: 0
      },
      // 主標題
      {
        id: 'text-1',
        type: 'text',
        content: 'CELEBRATION',
        x: 50,
        y: 100,
        width: 275,
        height: 70,
        zIndex: 1,
        fontSize: 38,
        fontFamily: 'sans-serif',
        color: '#ffffff',
        fontWeight: 900,
        textAlign: 'center',
      },
      // 副標題
      {
        id: 'text-2',
        type: 'text',
        content: '特別邀請',
        x: 50,
        y: 180,
        width: 150,
        height: 40,
        zIndex: 1,
        fontSize: 24,
        fontFamily: 'sans-serif',
        color: '#fbbf24',
        fontWeight: 600,
        textAlign: 'center',
      },
      // 活動資訊
      {
        id: 'text-3',
        type: 'text',
        content: '我們誠摯地邀請您參加\n這個特別的慶祝活動',
        x: 50,
        y: 350,
        width: 275,
        height: 80,
        zIndex: 1,
        fontSize: 20,
        fontFamily: 'sans-serif',
        color: '#ffffff',
        fontWeight: 400,
        textAlign: 'center',
      },
      // 日期時間
      {
        id: 'text-4',
        type: 'text',
        content: '12.20 / 19:00',
        x: 50,
        y: 470,
        width: 200,
        height: 40,
        zIndex: 1,
        fontSize: 28,
        fontFamily: 'monospace',
        color: '#fbbf24',
        fontWeight: 700,
        textAlign: 'center',
      },
      // RSVP 表單
      {
        id: 'rsvp-1',
        type: 'rsvp-form',
        x: 37,
        y: 560,
        width: 300,
        height: 80,
        zIndex: 1,
        fields: {
          name: true,
          email: true,
          attendance: true,
        },
      },
    ],
  },
];
